# Generated by Django 4.1.1 on 2022-10-17 02:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=b'I01\n', verbose_name='Image'),
            preserve_default=b'I01\n',
        ),
    ]
